name: workflow1

on:
  push:
    paths:
      - 'scripts/session_6/hello_world.txt'
  pull_request:
    paths:
      - 'scripts/session_6/pull_request_test.txt'
  workflow_dispatch:
    inputs:
      runner:
        description: 'who runs this workflow?'
        required: true
        default: 'ubuntu-latest'

jobs:
  workflow1_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display file content
        #run: cat scripts/session_6/hello_world.txt
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
            echo "This is a push event. Displaying hello_world.txt content:"
            cat scripts/session_6/hello_world.txt
          elif [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            echo "This is a pull request event. Displaying pull_request_test.txt content:"
            cat scripts/session_6/pull_request_test.txt
          else
            echo {{ github.event.inputs.runner }}
          fi